# -*- mode: Python; -*- scons script

import os, platform, shutil

Import('env', 'test_val')

def copyLibBuilder( target, source, env):
   '''kopiuje biblioteke'''
   shutil.copy( str(source[0]), str(target[0]) )
   return

#sciezki
env.Append( ENV = {'PATH' : os.environ['PATH'] })

if(platform.system() == "Linux"):
   env.Append( CPPPATH = ['/usr/include/python2.7'] )
   env.Append( LIBPATH = ['/usr/lib/python2.7'] )

   env.Append( CPPFLAGS = '-Wall -std=c++11 -pedantic -pthread' )
   env.Append( LINKFLAGS = '-Wall -pthread' )

   env.Append( LIBS = [ 'boost_python' ] )
elif(platform.system() == "Windows"):
   env.Append( CPPPATH = [ Dir('C:/Boost/include/boost-1_52'), #path to boost include
                           Dir('C:/Python27/include') ] ) #path to python include
   env.Append( LIBPATH = [ Dir('C:/Boost/lib'), #path to boost libs
                           Dir('C:/Python27/libs') ] ) #path to python libs

   env.Append( CPPFLAGS = ' /EHsc /MD /D "WIN32" /D "_CONSOLE" /W4' )
   env.Append( LINKFLAGS = ' /SUBSYSTEM:WINDOWS ' )
else:
   print platform.system() + " not supported"

#build C++ library
cpplib = env.SharedLibrary( target = 'checkers', source = ['src/CheckersPy.cpp', 'src/Checkers.cpp', 'src/Player.cpp', 'src/Board.cpp', 'src/Piece.cpp',
'src/Pawn.cpp', 'src/King.cpp', 'src/Move.cpp'])
if(platform.system() == "Linux"):
   target = '../build_web/checkerspy/checkers.so'
elif(platform.system() == "Windows"):
   target = '../build_web/checkerspy/checkers.pyd'
env.Command(target, cpplib, copyLibBuilder )

# build tests
#SConscript('test/SConscript', variant_dir='build', duplicate=0, exports=['env'])

# run tests
#if int(test_val):
#    print('scons: Running unit tests ...')
#    os.system('./build/test')
#    print('scons: done running tests.')
    
